src/Entity/Config.php
<?php

namespace App\Entity;

use App\Repository\ConfigRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="config", indexes={@ORM\Index(name="config_search_idx", columns={"name"})})
 * @ORM\Entity(repositoryClass=ConfigRepository::class)
 * @UniqueEntity("name")
 */
class Config
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", unique=true)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $name;

    /**
     * @ORM\Column(type="json")
     */
    private $value = [];

    public function getType()
    {
        if (isset($this->value['type'])) {
            return $this->value['type'];
        }

        return '';
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function get()
    {
        switch ($this->getType()) {
            case 'integer': return intval($this->value['value']);
            case 'number': return floatval($this->value['value']);
            default: return $this->value['value'];
        }
    }

    public function getRealType()
    {
        return gettype($this->get());
    }

    public function display()
    {
        if (!isset($this->value['type'])) {
            return '';
        }
        if ('json' == $this->value['type']) {
            return json_encode($this->value['value'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        } elseif ('integer' == $this->value['type']) {
            return (string) intval($this->value['value']);
        } elseif ('number' == $this->value['type']) {
            return (string) floatval($this->value['value']);
        }

        return $this->value['value'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getValue(): ?array
    {
        return $this->value;
    }

    public function setValue(array $value): self
    {
        $this->value = $value;

        return $this;
    }
}

src/Form/Back/ConfigType.php
<?php

namespace App\Form\Back;

use App\Entity\Config;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Json;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Validation;

class ConfigType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $config = $builder->getData();

        $builder
            ->add('name', TextType::class, [
                'label' => 'config.label.name',
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'config.label.type',
                'choices' => [
                    'string' => 'string',
                    'integer' => 'integer',
                    'number' => 'number',
                    'json' => 'json',
                ],
                'data' => $config->getType(),
                'mapped' => false,
            ])
            ->add('value', TextareaType::class, [
                'label' => 'config.label.value',
                'data' => $config->display(),
                'mapped' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Config::class,
            'translation_domain' => 'back_messages',
            'constraints' => [
                new Callback([$this, 'validate']),
            ],
        ]);
    }

    /**
     * Callback
     * Validation dynamique du formulaire sur plusieurs champs.
     *
     * @param array $data
     */
    public function validate($data, ExecutionContextInterface $context)
    {
        /**
         * @var \Symfony\Component\Form\Form $form
         */
        $form = $context->getRoot();
        if ('json' == $form->get('type')->getData()) {
            $validator = Validation::createValidator();
            $violations = $validator->validate($form->get('value')->getData(), [new Json([])]);
            if (0 !== count($violations)) {
                foreach ($violations as $violation) {
                    $form->get('value')->addError(new FormError($violation->getMessage()));
                }
            }
        }
    }
}

src/Controller/Back/ConfigController.php
<?php

namespace App\Controller\Back;

use App\Entity\Config;
use App\Form\Back\ConfigBatchType;
use App\Form\Back\ConfigFilterType;
use App\Form\Back\ConfigType;
use App\Manager\Back\ConfigManager;
use App\Repository\ConfigRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/back/config")
 */
class ConfigController extends AbstractController
{
    /**
     * @var ConfigRepository     */
    private $configRepository;

    /**
     * @var ConfigManager     */
    private $configManager;

    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(ConfigRepository $configRepository, ConfigManager $configManager, TranslatorInterface $translator)
    {
        $this->configRepository = $configRepository;
        $this->configManager = $configManager;
        $this->translator = $translator;
    }

    /**
     * @Route("/search/{page}", name="back_config_search", methods="GET|POST")
     */
    public function search(Request $request, Session $session, $page = null)
    {
        if (!$page) {
            $page = $session->get('back_config_page', 1);
        }
        $formFilter = $this->createForm(ConfigFilterType::class, null, ['action' => $this->generateUrl('back_config_search', ['page' => 1])]);
        $formFilter->handleRequest($request);
        $data = $this->configManager->configFormFilter($formFilter)->getData();
        $configs = $this->configRepository->searchBack($request, $session, $data, $page);
        $queryData = $this->configManager->getQueryData($data);
        $formBatch = $this->createForm(ConfigBatchType::class, null, [
            'action' => $this->generateUrl('back_config_search', array_merge(['page' => $page], $queryData)),
            'configs' => $configs,
        ]);
        $formBatch->handleRequest($request);
        if ($formBatch->isSubmitted() && $formBatch->isValid()) {
            $url = $this->configManager->dispatchBatchForm($formBatch);
            if ($url) {
                return $this->redirect($url);
            }
        }

        return $this->render('back/config/search/index.html.twig', [
            'configs' => $configs,
            'form_filter' => $formFilter->createView(),
            'form_batch' => $formBatch->createView(),
            'form_delete' => $this->createFormBuilder()->getForm()->createView(),
            'number_page' => ceil(count($configs) / $formFilter->get('number_by_page')->getData()) ?: 1,
            'page' => $page,
            'query_data' => $queryData,
        ]);
    }

    /**
     * @Route("/create", name="back_config_create", methods="GET|POST")
     */
    public function create(Request $request): Response
    {
        $config = new Config();
        $form = $this->createForm(ConfigType::class, $config);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $this->configManager->setValue($config, $form);
            $em->persist($config);
            $em->flush();
            $msg = $this->translator->trans('config.create.flash.success', ['%identifier%' => $config], 'back_messages');
            $this->addFlash('success', $msg);

            return $this->redirectToRoute('back_config_search');
        }

        return $this->render('back/config/create.html.twig', [
            'config' => $config,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/read/{id}", name="back_config_read", methods="GET")
     */
    public function read(Config $config): Response
    {
        return $this->render('back/config/read.html.twig', [
            'config' => $config,
        ]);
    }

    /**
     * @Route("/update/{id}", name="back_config_update", methods="GET|POST")
     */
    public function update(Request $request, Config $config): Response
    {
        $form = $this->createForm(ConfigType::class, $config);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->configManager->setValue($config, $form);
            $this->getDoctrine()->getManager()->flush();
            $msg = $this->translator->trans('config.update.flash.success', [], 'back_messages');
            $this->addFlash('success', $msg);

            return $this->redirectToRoute('back_config_search');
        }

        return $this->render('back/config/update.html.twig', [
            'config' => $config,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete", name="back_config_delete", methods="GET|POST")
     */
    public function delete(Request $request): Response
    {
        $configs = $this->configManager->getConfigs();
        $formBuilder = $this->createFormBuilder();
        $formBuilder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($configs) {
            $result = $this->configManager->validationDelete($configs);
            if (true !== $result) {
                $event->getForm()->addError(new FormError($result));
            }
        });
        $form = $formBuilder->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            foreach ($configs as $config) {
                $em->remove($config);
            }
            try {
                $em->flush();
                $this->addFlash('success', $this->translator->trans('config.delete.flash.success', [], 'back_messages'));
            } catch (\Doctrine\DBAL\DBALException $e) {
                $this->addFlash('warning', $e->getMessage());
            }

            return $this->redirectToRoute('back_config_search');
        }

        return $this->render('back/config/delete.html.twig', [
            'configs' => $configs,
            'form' => $form->createView(),
        ]);
    }
}

templates/Back/config/search/_filter.html.twig
{% trans_default_domain 'back_messages' %}
<div class="card p-2 mb-2">
    <div class="card-body">
        {{ form_start(form_filter) }}
            <div class="row">
                <div class="col-lg-4">
                    {{ form_row(form_filter.search) }}
                </div>
                <div class="col-lg-4">
                    {{ form_row(form_filter.number_by_page) }}
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <button id="filter_submit" class="btn bg-white text-primary btn-block button">
                            <i class="fas fa-filter"></i> {{ 'button.filter'|trans() }}
                        </button>
                    </div>
                </div>
            </div>
        {{ form_end(form_filter) }}
    </div>
</div>

templates/Back/config/search/_list.html.twig
{% trans_default_domain 'back_messages' %}

{% set col_count = 3 %}

{% if can_multi_select %}
    {{ form_start(form_batch) }}
    {{ form_errors(form_batch) }}
{% endif %}
<div class="card mt-4 mb-4">
    <div class="card-body">
        <h2 class="card-title">{{ 'config.search.h2'|trans() }}</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        {% if can_multi_select %}
                            {% set col_count = col_count + 1 %}
                            <th><div class="form-check pl-0"><input type="checkbox" id="select_all" /></div></th>
                        {% endif %}
                        <th>{{ 'search.action_th'|trans() }}</th>
                        <th>{{ 'config.field.name'|trans() }}</th>
                        <th>{{ 'config.field.type'|trans() }}</th>
                        <th>{{ 'config.field.value'|trans() }}</th>
                    </tr>
                </thead>
                <tbody>
                {% for child in form_batch.configs %}
                    {% set config = form_batch.configs.vars.choices[child.vars.value].data %}
                    <tr>
                        {% if can_multi_select %}
                            <td>
                                {{ form_row(child, { 'attr': { 'class': 'select'}}) }}
                            </td>
                        {% endif %}
                        <td>
                            {% if can_read %}
                                <a href="{{ path('back_config_read', {'id': config.id}) }}" title="{{ 'button.read_title'|trans() }}"
                                    class="btn bg-white text-primary button" aria-label="{{ 'button.read_title'|trans() }}" role="button">
                                    <i class="fas fa-file-alt"></i>
                                </a>
                            {% endif %}
                            {% if can_update %}
                                <a href="{{ path('back_config_update', {'id': config.id}) }}" title="{{ 'button.update_title'|trans() }}"
                                    class="btn bg-white text-warning button" aria-label="{{ 'button.update_title'|trans() }}" role="button">
                                    <i class="fas fa-edit"></i>
                                </a>
                            {% endif %}
                            {% if can_delete %}
                                <a href="#" class="btn bg-white text-danger btn-delete button" data-toggle="modal" data-target="#delete"
                                    data-title="{{ config }}" role="button"
                                    data-path="{{ path('back_config_delete', { 'ids': {0: config.id}}) }}"
                                    title="{{ 'button.delete_title'|trans() }}" aria-label="{{ 'button.delete_title'|trans() }}">
                                    <i class="fas fa-times"></i>
                                </a>
                            {% endif %}
                        </td>
                        <td>{{ config.name }}</td>
                        <td>{{ config.type ~ ' / ' ~ config.realType }}</td>
                        <td><pre>{{ config.display }}</pre></td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="{{ col_count }}">{{ 'search.no_data_found'|trans() }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if can_multi_select %}
    <div class="card p-2 mt-2">
        <div class="card-body">
            <div class="row">
                <div class="col-md-9 col-lg-9">
                    {{ form_row(form_batch.action) }}
                </div>
                <div class="col-md-3 col-lg-3">
                    <div class="text-center">
                        <button id="submit" class="btn bg-white text-primary btn-block button">{{ 'button.validate'|trans() }}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form_batch) }}
{% endif %}

templates/Back/config/search/_pagination.html.twig
{% trans_default_domain 'back_messages' %}
{% if number_page > 1 %}
{% if page > 1 %}
    {% set previous = page - 1 %}
{% endif %}
{% if page < number_page %}
    {% set next = page + 1 %}
{% endif %}
{% set range_start = page - 2 %}
{% if range_start < 1 %}
    {% set range_start = 1 %}
{% endif %}
{% set range_end = page + 2 %}
{% if range_end > number_page %}
    {% set range_end = number_page %}
{% endif %}
<div class="mt-4">
    <nav>
        <ul class="pagination justify-content-center pagination-sm">
            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" href="{{ path('back_config_search', { 'page' : previous }|merge(query_data)) }}">&laquo;&nbsp;{{ 'button.previous'|trans() }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&nbsp;{{ 'button.previous'|trans() }}</span>
                </li>
            {% endif %}
            {% if range_start > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('back_config_search', { 'page' : 1 }|merge(query_data)) }}">1</a>
                </li>
                {% if range_start == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path('back_config_search', { 'page' : 2 }|merge(query_data)) }}">2</a>
                    </li>
                    {% elseif range_start != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}
            {% set pages = [] %}
            {% if (range_start -1) > 10 %}
                {% set ten = range_start - range_start % 10 %}
                {% if ten > 1 %}
                    {% for i in 1..3 %}
                        {% if ten != range_start %}
                            {% set pages = ([ten]|merge(pages)) %}
                        {% endif %}
                        {% set ten = (range_start - i * 10) - (range_start - i * 10) % 10 %}
                    {% endfor %}
                {% endif %}
                {% if ten > 100 %}
                    {% set hundred = (ten) - (ten) % 100 %}
                    {% if hundred > 1 %}
                        {% for i in 1..3 %}
                            {% set pages = [hundred]|merge(pages) %}
                            {% set hundred = (ten - i * 100) - (ten - i * 100) % 100 %}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for p in pages %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('back_config_search', { 'page' : p }|merge(query_data)) }}">{{ p }}</a>
                </li>
            {% endfor %}
            {% for p in range_start..range_end %}
                {% if p == page %}
                    <li class="page-item active">
                        <span class="page-link">{{ p }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path('back_config_search', { 'page' : p }|merge(query_data)) }}">{{ p }}</a>
                    </li>
                {% endif %} 
            {% endfor %}
            {% if (number_page - range_end) > 10 %}
                {% set ten = (range_end + 10) - (range_end + 10) % 10 %}
                {% if ten < number_page %}
                    {% for i in 2..4 %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path('back_config_search', { 'page' : ten }|merge(query_data)) }}">{{ ten }}</a>
                        </li>
                        {% set ten = (range_end + i * 10) - (range_end + i * 10) % 10 %}
                    {% endfor %}
                {% endif %}
                {% if (number_page - ten) > 100 %}
                    {% set hundred = (ten + 100) - (ten + 100) % 100 %}
                    {%  if hundred < number_page %}
                        {% for i in 2..4 %}
                            <li class="page-item">
                                <a class="page-link" href="{{ path('back_config_search', { 'page' : hundred }|merge(query_data)) }}">{{ hundred }}</a>
                            </li>
                            {% set hundred = (ten + i * 100) - (ten + i * 100) % 100 %}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            {% endif %}
            {% if number_page > range_end %}
                {% if number_page > (range_end + 1) %}
                    {% if number_page > (range_end + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path('back_config_search', { 'page' : number_page - 1 }|merge(query_data)) }}">{{ number_page - 1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('back_config_search', { 'page' : number_page }|merge(query_data)) }}">{{ number_page }}</a>
                </li>
            {% endif %}
            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" href="{{ path('back_config_search', { 'page' : next }|merge(query_data)) }}">{{ 'button.next'|trans() }}&nbsp;&raquo;</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">{{ 'button.next'|trans() }}&nbsp;&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

templates/Back/config/search/index.html.twig
{% trans_default_domain 'back_messages' %}
{% extends "back/layout.html.twig" %}

{% set can_create = true %}
{% set can_read = true %}
{% set can_update = true %}
{% set can_delete = true %}
{% set can_filter = true %}
{% set can_multi_select = true %}

{% block title %}{{ 'config.search.title'|trans() }}{% endblock %}

{% block content %}
{% if can_delete %}
    <div id="delete" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modal_title" class="modal-title">{{ 'config.delete.modal_title'|trans() }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="X">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modal_body" class="modal-body">
                    <h6 id="modal_body_title"></h6>
                    <div class="alert alert-warning">
                        <strong>{{ 'delete.warning'|trans() }}</strong>
                    </div>
                </div>
                <div id="modal_footer" class="modal-footer">
                    {{ form_start(form_delete, {'attr': {'id': 'form_back_config_delete' }}) }}
                        <button type="submit" class="btn bg-white text-danger button">{{ 'button.delete'|trans() }}</button>
                    {{ form_end(form_delete) }}
                    <button type="button" class="btn btn-secondary button" data-dismiss="modal">{{ 'button.cancel'|trans() }}</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}
<section class="pt-4 pb-4">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1 class="h3">{{ 'config.search.h1'|trans() }}</h1>
            </div>
            <div class="col-sm-6 text-right">
                <p>
                    {% if can_create %}
                        <a href="{{ path('back_config_create') }}" class="btn bg-white text-primary button">
                            <i class="fas fa-plus"></i> {{ 'button.create'|trans() }}
                        </a>
                    {% endif %}
                </p>
            </div>
        </div>
        <hr>

        {% if can_filter %}
            {{ include('back/config/search/_filter.html.twig') }}
        {% endif %}

        {{ include('back/config/search/_list.html.twig') }}

        {{ include('back/config/search/_pagination.html.twig') }}

    </div>
</section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {% if can_delete %}
        <script>
            $(document).ready(function(){
                $('.btn-delete').click(function(){
                    var title = $(this).attr('data-title');
                    var path = $(this).attr('data-path');
                    $('#form_back_config_delete').attr('action', path);
                    $('#modal_body_title').html("{{ 'delete.confirm'|trans() }} : <strong>"+title+"</strong>");
                });
            });
        </script>
    {% endif %}

    {% if can_multi_select %}
        <script>
            $(document).ready(function(){
                $("#check_all").click(function(){
                    $('input:checkbox').not(this).prop('checked', this.checked);
                });
                $("#select_all").change(function() {
                    if (this.checked) {
                        $(".select").each(function() {
                            this.checked=true;
                        });
                    } else {
                        $(".select").each(function() {
                            this.checked=false;
                        });
                    }
                });
            });
        </script>
    {% endif %}

{% endblock %}