src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=256)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToOne(targetEntity=File::class, cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $croppedImageName;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $croppedImageThumbnailName;

    /**
     * @ORM\OneToMany(targetEntity=ArticlePositionCategory::class, mappedBy="article", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"positionCategory" = "ASC"})
     */
    private $positionCategories;

    public function __construct()
    {
        $this->positionCategories = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getCategories()
    {
        $categories = [];
        foreach ($this->getPositionCategories() as $positionCategory) {
            $categories[] = $positionCategory->getCategory();
        }

        return $categories;
    }

    public function removeCategory($category)
    {
        foreach ($this->getPositionCategories() as $positionCategory) {
            if ($category === $positionCategory->getCategory()) {
                $this->removePositionCategory($positionCategory);
                $positionCategory->getCategory()->removePositionArticle($positionCategory);

                return true;
            }
        }

        return false;
    }

    public function computeSlug(SluggerInterface $slugger)
    {
        if (!$this->slug || '-' === $this->slug) {
            $this->slug = (string) $slugger->slug((string) $this)->lower();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getImage(): ?File
    {
        return $this->image;
    }

    public function setImage(?File $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCroppedImageName(): ?string
    {
        return $this->croppedImageName;
    }

    public function getCroppedImageAlt(): ?string
    {
        $alt = substr($this->croppedImageName, strpos($this->croppedImageName, '___') + 3);

        return substr($alt, 0, strpos($alt, '.'));
    }

    public function setCroppedImageName(?string $croppedImageName): self
    {
        $this->croppedImageName = $croppedImageName;

        return $this;
    }

    public function getCroppedImageThumbnailName(): ?string
    {
        return $this->croppedImageThumbnailName;
    }

    public function getCroppedImageThumbnailAlt(): ?string
    {
        $alt = substr($this->croppedImageThumbnailName, strpos($this->croppedImageThumbnailName, '___') + 3);

        return substr($alt, 0, strpos($alt, '.'));
    }

    public function setCroppedImageThumbnailName(?string $croppedImageThumbnailName): self
    {
        $this->croppedImageThumbnailName = $croppedImageThumbnailName;

        return $this;
    }

    /**
     * @return Collection|ArticlePositionCategory[]
     */
    public function getPositionCategories(): Collection
    {
        return $this->positionCategories;
    }

    public function addPositionCategory(ArticlePositionCategory $positionCategory): self
    {
        if (!$this->positionCategories->contains($positionCategory)) {
            $this->positionCategories[] = $positionCategory;
            $positionCategory->setArticle($this);
        }

        return $this;
    }

    public function removePositionCategory(ArticlePositionCategory $positionCategory): self
    {
        if ($this->positionCategories->removeElement($positionCategory)) {
            // set the owning side to null (unless already changed)
            if ($positionCategory->getArticle() === $this) {
                $positionCategory->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/Front/ContactMessageType.php
<?php

namespace App\Form\Front;

use App\Entity\ContactMessage;
use App\Form\Recaptcha3SubmitType;
use App\Repository\ConfigRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactMessageType extends AbstractType
{
    private $recaptchaActivated;

    public function __construct(ConfigRepository $configRepository)
    {
        $this->recaptchaActivated = $configRepository->findOneByName('app')->get()['recaptcha_activated'];
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => 'contact_message.label.firstname',
            ])
            ->add('lastname', TextType::class, [
                'label' => 'contact_message.label.lastname',
            ])
            ->add('email', EmailType::class, [
                'label' => 'contact_message.label.email',
            ])
            ->add('phone', TelType::class, [
                'label' => 'contact_message.label.phone',
            ])
            ->add('subject', TextType::class, [
                'label' => 'contact_message.label.subject',
            ])
            ->add('message', TextareaType::class, [
                'label' => 'contact_message.label.message',
                'attr' => [
                    'rows' => '5',
                    'cols' => '50',
                ],
            ]);
        if ($this->recaptchaActivated) {
            $builder
            ->add('submit', Recaptcha3SubmitType::class, [
                'parent_builder' => $builder,
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ContactMessage::class,
            'translation_domain' => 'front_messages',
        ]);
    }
}

src/Form/Front/RegistrationFormType.php
<?php

namespace App\Form\Front;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class RegistrationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'registration.label.email',
            ])
            ->add('firstname', TextType::class, [
                'label' => 'registration.label.firstname',
            ])
            ->add('lastname', TextType::class, [
                'label' => 'registration.label.lastname',
            ])
            ->add('plainPassword', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'registration.message.repeated_password_invalid',
                'options' => ['attr' => ['class' => 'password-field']],
                'required' => true,
                'first_options' => ['label' => 'registration.label.password'],
                'second_options' => ['label' => 'registration.label.repeat_password'],
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'constraints' => [
                    new NotBlank([
                        'message' => 'registration.message.password_not_blank',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'registration.message.password_length_min',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('agreeTerms', CheckboxType::class, [
                'label' => 'registration.label.agree_terms',
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'registration.message.agree_terms_is_true',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'translation_domain' => 'security',
        ]);
    }
}

src/Controller/Front/PageController.php
<?php

namespace App\Controller\Front;

use App\Entity\Article;
use App\Entity\ContactMessage;
use App\Form\Front\ContactMessageType;
use App\Mailer\Mailer;
use App\Repository\ArticleCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class PageController extends AbstractController
{
    /**
     * @Route("/", name="front_home")
     */
    public function index(ArticleCategoryRepository $articleCategoryRepository)
    {
        return $this->render('front/page/index.html.twig', [
            'categories' => $articleCategoryRepository->findByDisplayedHome(true),
        ]);
    }

    /**
     * @Route("/contact", name="front_page_contact", methods="GET|POST")
     */
    public function contact(Request $request, TranslatorInterface $translator, Mailer $mailer)
    {
        $contactMessage = new ContactMessage();
        $form = $this->createForm(ContactMessageType::class, $contactMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($contactMessage);
            $em->flush();
            $mailer->sendContactMessage($contactMessage);
            $msg = $translator->trans('contact_message.create.flash.success', [], 'front_messages');
            $this->addFlash('success', $msg);

            return $this->redirectToRoute('front_home');
        }

        return $this->render('front/page/contact.html.twig', [
            'contact_message' => $contactMessage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", priority=-100, name="front_page_article", methods="GET")
     */
    public function article(Article $article)
    {
        return $this->render('front/page/article.html.twig', [
            'article' => $article,
        ]);
    }
}

src/Controller/Front/RegistrationController.php
<?php

namespace App\Controller\Front;

use App\Entity\User;
use App\Form\Front\RegistrationFormType;
use App\Mailer\Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class RegistrationController extends AbstractController
{
    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/register", name="front_register")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, Mailer $mailer): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $user->setEnabled(false);
            $user->setConfirmationToken('register_'.bin2hex(random_bytes(24)));
            $user->setLastLoginAt(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            $mailer->sendRegistration($user, $request->getLocale());

            $msg = $this->translator->trans('registration.flash.check_email', ['%email%' => $user->getEmail()], 'security');
            $this->addFlash('info', $msg);

            return $this->redirectToRoute('app_login');
        }

        return $this->render('front/registration/register.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/Front/page/article.html.twig
{% trans_default_domain 'front_messages' %}
{% extends "front/layout.html.twig" %}

{% block title %}{{ article.title }}{% endblock %}

{% block description %}{{ article.description }}{% endblock %}

{% block content %}
    <section class="pt-4 pb-4">
        <div class="container">
            <div class="d-flex flex-column flex-sm-row justify-content-between">
                {% if article.croppedImageName %}
                    <div class="text-center"><img src="/upload/{{ article.croppedImageName }}" alt="{{ article.croppedImageAlt }}" class="img-fluid"></div><br>
                {% endif %}
                <div class="card mt-4 mb-4">
                    <div class="card-body">
                        <h1 class="card-title">{{ article.title }}</h1>
                        <div class="card-content">
                            
                            <ul class="list-unstyled">        
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.author'|trans() }} : </strong>{{ article.author }}                            
                                </li>
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.created_at'|trans() }} : </strong>{{ article.createdAt ? article.createdAt|format_datetime : '' }}
                                </li>
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.updated_at'|trans() }} : </strong>{{ article.updatedAt ? article.updatedAt|format_datetime : '' }}
                                </li>
                            </ul>
                        </div>
                    </div>        
                </div>
            </div>

            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <div class="card-content">
                        <div class="text-justify">{{ article.content|raw }}</div>
                    </div>
                </div>
            </div>
            
        </div>
    </section>
{% endblock %}

templates/Front/page/contact.html.twig
{% trans_default_domain 'front_messages' %}
{% extends "front/layout.html.twig" %}

{% block title %}
    {{ 'contact_message.create.title'|trans() }}
{% endblock %}

{% block content %}
    <section class="pt-4 pb-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="h3">{{ 'contact_message.create.h1'|trans() }}</h1>
                </div>
                <div class="col-sm-6 text-right">
                </div>
            </div>
            <hr>
            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ 'contact_message.create.h2'|trans() }}</h2>
                    <div class="p-4 border border-light">
                        {{ form_start(form, { attr: { 'id': 'form_contact' }}) }}
                        {{ form_errors(form) }}
                        {{ form_row(form.firstname) }}
                        {{ form_row(form.lastname) }}
                        {{ form_row(form.email) }}
                        {{ form_row(form.phone) }}
                        {{ form_row(form.subject) }}
                        {{ form_row(form.message) }}
                        {% if form.submit is defined %}
                            {{ form_row(form.submit) }}
                        {% else %}
                            <button class="btn btn-info btn-block">
                                <i class="far fa-paper-plane"></i>
                                Envoyer
                            </button>
                        {% endif %}
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/Front/page/index.html.twig
{% extends 'front/layout.html.twig' %}
{% trans_default_domain 'front_messages' %}
{% block title %}{% endblock %}

{% block content %}
    {% for category in categories %}
        <h2><span>{{ category.name }}</span></h2>
        {% for article in category.articles %}
            <div class="media d-flex flex-column flex-sm-row">
                {% if article.croppedImageThumbnailName %}
                    <img class="align-self-start mr-3 mb-5" src="{{ article.croppedImageThumbnailName }}" alt="{{ article.croppedImageThumbnailAlt }}">
                {% endif %}
                <div class="media-body">
                    <h3>{{ article.title }}</h3>
                    <div class="text-justify">{{ article.description|nl2br }}</div>
                    <p class="mb-0">
                        <a href="{{ path('front_page_article', { 'slug': article.slug }) }}" aria-label="{{ 'article.button.more'|trans }}" role="button">
                            <i class="fas fa-file-alt"></i>
                        </a>
                    </p>
                </div>
            </div>
            <hr class="pt-3 mt-3 color_bluesky">        
        {% endfor %}       
    {% endfor %}
{% endblock %}